### ISSUE TITLE
Wrong time translation French language

### ISSUE THREAD

**Issue by Nightsax** [jeanropke/RDR2CollectorsMap#1003]
Night spawning special flowers (Agarita for ex) has a spawn time from 10pm-5pm (17 heures) instead of 10pm-5am (5 heures) in the French translation. English shows correct time. Little mistake but please correct. Thanks

**Comment by MichalD96** [comment]
I corrected this one, but you can make corrections by your own here: 
https://crowdin.com/project/rdr2collectorsmap

**Comment by Nightsax** [comment]
Ok thanks, but somehow the error remains, 22h-17h still written. I have already refreshed the map but no change.

**Comment by MichalD96** [comment]
yes, translations are updated automatically and all changes will be visible in around 30 min.
