### ISSUE TITLE
[Bug report] Automatic daily marker reset doesn't seem to work

### ISSUE THREAD

**Issue by Rakmarok** [jeanropke/RDR2CollectorsMap#143]
It seems like the daily marker reset doesn't work automatically when you manually hid markers the day before.

**Comment by jeanropke** [comment]
I think it's fixed now.

**Comment by Rakmarok** [comment]
I accessed the map first time today and the markers I disabled yesterday are still disabled.

![image](https://user-images.githubusercontent.com/55949253/66291740-de385f00-e8e2-11e9-85ef-43ef30b69ea3.png)

Thank you for looking into this.

**Comment by jeanropke** [comment]
Fixed now

**Comment by Rakmarok** [comment]
I apologize for the inconvenience but it still isn't working for me. Could it be on my end?

![image](https://user-images.githubusercontent.com/55949253/66469730-ae2ac080-ea88-11e9-9c33-6c2c3cb69d75.png)

I reloaded the map multiple times (with and without CTRL).

**Comment by jeanropke** [comment]
You always keep the reset markers daily enabled?

**Comment by Rakmarok** [comment]
Yes, I always enable it manually after resetting the markers.

**Comment by jeanropke** [comment]
Reset markers only works if the options is enable before the day/cycle chance.
I'll do some tests again.

**Comment by Rakmarok** [comment]
> Reset markers only works if the options is enable before the day/cycle chance.
> I'll do some tests again.

It always is. 🤔

**Comment by githb123** [comment]
I have the same. Just reloaded the map (F5) and some items from my previous visits where dimmed. After I deleted the cookies in the browser and reloaded the map they're now all solid/active.

**Comment by jeanropke** [comment]
I changed again. Can confirm if its working?
